### ISSUE TITLE
Añade un archivo requirements.txt 

### ISSUE THREAD

**Issue by davevad93** [anzit1/WeatherApp#1]
Hola @anzit1, 

Deberías crear un archivo `requirements.txt` para automatizar la instalación de paquetes y dependencias ejecutando el comando 
`pip freeze > requirements.txt`

**Comment by anzit1** [comment]
A/S/L?

**Comment by anzit1** [comment]
> Hola @anzit1,
> 
> Deberías crear un archivo `requirements.txt` para automatizar la instalación de paquetes y dependencias ejecutando el comando `pip freeze > requirements.txt`

A/S/L?
